---
# tasks file for ec2_role
- name: Start an Instance with public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    instance_type: "{{ type }}"
    security_group: default
    region: us-east-1
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network:
      assign_public_ip: true
    image_id: ami-0e86e20dae9224db8


